#!/usr/bin/env bash

set -euo pipefail

host="${INST_TARGET_HOST:?}"
flakedir="${INST_FLAKE_DIR:?}"

set -x

sudo mkdir -p /mnt/persist/etc/ssh
sudo cp -a /etc/machine-id /mnt/persist/etc/
# Copy user password files previously created into /tmp/persist
sudo cp -ar /tmp/persist /mnt/

if command -v my-preinstall-$host &> /dev/null; then
    my-preinstall-$host
else
    echo "No host-specific pre-install hook found." >&2
fi

sudo nixos-install --flake "$flakedir#$host" --no-root-passwd

if command -v my-postinstall-$host &> /dev/null; then
    my-postinstall-$host
else
    echo "No host-specific post-install hook found." >&2
fi

sudo cp -ar /mnt/etc/ssh/authorized_keys.d /mnt/persist/etc/ssh/
