#!/usr/bin/env bash
# Dependencies: wget unzip

set -euo pipefail

version=1.35
archive="RPi4_UEFI_Firmware_v$version.zip"
url="https://github.com/pftf/RPi4/releases/download/v$version/$archive"
set -x

# Download and install RPi4 UEFI firmware image

cd /mnt/boot
sudo wget "$url"
sudo unzip "$archive"
sudo rm *.md "$archive"
